server:
  port: 8080
spring:
  application:
    name: modules-demo
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #serverTimezone=GMT%2B8时区，GMT%2B8北京东八区，也可以设置Asia/Shanghai
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        enabled: true
        url-pattern: "/druid/**"
        login-username: admin
        login-password: admin
  # 解决Swagger与2.6以上springboot不兼容
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#指定mybatis的mapper扫描路径
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
    - classpath*:com/**/dao/*.xml